### ISSUE TITLE
Add shop ID to sku

### ISSUE THREAD

**Issue by ZenImagine** [drugan/commerce_multistore#4]
It would be nice to automatically add the store ID to the product reference.

For a product with the reference 015:

sku-015

With the store ID 1:

sku-1-015

**Comment by drugan** [comment]
That's a great idea but it is more for the [#2755529: Product variant bulk creation](https://www.drupal.org/node/2755529) which itself depends on the auto generated SKU. The Multistore module initially was designed to handle multiple stores/store owners issues. 

I have a plan to integrate [Token](https://www.drupal.org/project/token) module with the variation bulk creator. So, you can construct auto SKU like this: sku-[commerce_store:id]-[commerce_product:id]-[commerce_product:type]-[etc...].

What now blocks further developing of the creator is this issue: [#2901939: Move the variations form to its own tab next to (Product) Edit](https://www.drupal.org/node/2901939). As it lands then the creator should be totally rewritten in order to work with the new way of variations creation. But, I am not going to wait forever for the #2901939 landing or commiting the creator. If nothing happens on the issue then I'll make a variation bulk creator contrib as soon as I have a possibility for it.
